"""add_pipeline_fields_to_opportunities

Revision ID: 158805b46c25
Revises: b7463267d6ae
Create Date: 2026-01-11 18:14:08.137935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158805b46c25'
down_revision: Union[str, None] = 'b7463267d6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('pipeline_stage', sa.String(length=50), nullable=False, server_default='capture'))
    op.add_column('opportunities', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('opportunities', sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('hidden_reason', sa.String(length=500), nullable=True))
    op.add_column('opportunities', sa.Column('is_no_bid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('opportunities', sa.Column('no_bid_reason', sa.String(length=500), nullable=True))
    op.add_column('opportunities', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_opportunities_is_hidden'), 'opportunities', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_opportunities_pipeline_stage'), 'opportunities', ['pipeline_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_pipeline_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_hidden'), table_name='opportunities')
    op.drop_column('opportunities', 'is_favorite')
    op.drop_column('opportunities', 'no_bid_reason')
    op.drop_column('opportunities', 'is_no_bid')
    op.drop_column('opportunities', 'hidden_reason')
    op.drop_column('opportunities', 'hidden_at')
    op.drop_column('opportunities', 'is_hidden')
    op.drop_column('opportunities', 'pipeline_stage')
    # ### end Alembic commands ###
