"""add_company_compliance_to_analysis

Revision ID: 6edf5d26dd9d
Revises: cd0b3386b537
Create Date: 2026-01-11 22:41:31.602206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6edf5d26dd9d'
down_revision: Union[str, None] = 'cd0b3386b537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('company_compliance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'company_compliance')
    # ### end Alembic commands ###
