"""add_relevance_label

Revision ID: b7463267d6ae
Revises: e8f6913ee60d
Create Date: 2026-01-11 15:42:34.654367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7463267d6ae'
down_revision: Union[str, None] = 'e8f6913ee60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('overall_relevance_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'overall_relevance_label')
    # ### end Alembic commands ###
