"""add_govcon_fields_to_company

Revision ID: cd0b3386b537
Revises: 158805b46c25
Create Date: 2026-01-11 22:35:04.062935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd0b3386b537'
down_revision: Union[str, None] = '158805b46c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('business_size', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('certification_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('gsa_schedules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('contract_vehicles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('primary_naic_code', sa.String(length=6), nullable=True))
    op.add_column('companies', sa.Column('service_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('facility_clearance', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('geographic_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('annual_revenue', sa.BigInteger(), nullable=True))
    op.add_column('companies', sa.Column('bonding_capacity', sa.BigInteger(), nullable=True))
    op.add_column('companies', sa.Column('teaming_partners', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('typical_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'typical_role')
    op.drop_column('companies', 'teaming_partners')
    op.drop_column('companies', 'bonding_capacity')
    op.drop_column('companies', 'annual_revenue')
    op.drop_column('companies', 'geographic_coverage')
    op.drop_column('companies', 'facility_clearance')
    op.drop_column('companies', 'service_areas')
    op.drop_column('companies', 'primary_naic_code')
    op.drop_column('companies', 'contract_vehicles')
    op.drop_column('companies', 'gsa_schedules')
    op.drop_column('companies', 'certification_details')
    op.drop_column('companies', 'certifications')
    op.drop_column('companies', 'business_size')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'founded_year')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'linkedin_url')
    # ### end Alembic commands ###
