"""add_v2_analysis_fields

Revision ID: e8f6913ee60d
Revises: 06fcc5391ca4
Create Date: 2026-01-11 15:40:58.642682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8f6913ee60d'
down_revision: Union[str, None] = '06fcc5391ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('requirements_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('requirements_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('contract_assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('evaluator_perspective', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('dimensional_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_analyses_company', table_name='analyses', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_analyses_created', table_name='analyses', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_analyses_opportunity', table_name='analyses', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_analyses_score', table_name='analyses', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_analyses_company_id'), 'analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_analyses_opportunity_id'), 'analyses', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_analyses_overall_relevance_score'), 'analyses', ['overall_relevance_score'], unique=False)
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_index('idx_audit_company', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index('idx_companies_cage', table_name='companies', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_companies_name', table_name='companies', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_companies_uei', table_name='companies', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_companies_cage_code'), 'companies', ['cage_code'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_uei'), 'companies', ['uei'], unique=False)
    op.drop_index('idx_documents_company', table_name='documents', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_documents_customer', table_name='documents', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_documents_embedding', table_name='documents', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_documents_naics', table_name='documents', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_type', table_name='documents', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_customer_agency'), 'documents', ['customer_agency'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_naics_code'), 'documents', ['naics_code'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.drop_index('idx_opportunities_company', table_name='opportunities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_opportunities_due_date', table_name='opportunities', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_opportunities_status', table_name='opportunities', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_response_due_date'), 'opportunities', ['response_due_date'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.drop_index('idx_opp_docs_embedding', table_name='opportunity_documents', postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.drop_index('idx_opp_docs_opportunity', table_name='opportunity_documents')
    op.drop_index('idx_opp_docs_type', table_name='opportunity_documents')
    op.create_index(op.f('ix_opportunity_documents_document_type'), 'opportunity_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_opportunity_documents_opportunity_id'), 'opportunity_documents', ['opportunity_id'], unique=False)
    op.drop_index('idx_user_companies_company', table_name='user_companies')
    op.drop_index('idx_user_companies_user', table_name='user_companies')
    op.drop_constraint('user_companies_user_id_company_id_key', 'user_companies', type_='unique')
    op.create_index(op.f('ix_user_companies_company_id'), 'user_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_companies_user_id'), 'user_companies', ['user_id'], unique=False)
    op.drop_index('idx_users_auth_provider', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_users_auth_provider', 'users', ['auth_provider', 'auth_provider_id'], unique=False)
    op.drop_index(op.f('ix_user_companies_user_id'), table_name='user_companies')
    op.drop_index(op.f('ix_user_companies_company_id'), table_name='user_companies')
    op.create_unique_constraint('user_companies_user_id_company_id_key', 'user_companies', ['user_id', 'company_id'])
    op.create_index('idx_user_companies_user', 'user_companies', ['user_id'], unique=False)
    op.create_index('idx_user_companies_company', 'user_companies', ['company_id'], unique=False)
    op.drop_index(op.f('ix_opportunity_documents_opportunity_id'), table_name='opportunity_documents')
    op.drop_index(op.f('ix_opportunity_documents_document_type'), table_name='opportunity_documents')
    op.create_index('idx_opp_docs_type', 'opportunity_documents', ['document_type'], unique=False)
    op.create_index('idx_opp_docs_opportunity', 'opportunity_documents', ['opportunity_id'], unique=False)
    op.create_index('idx_opp_docs_embedding', 'opportunity_documents', ['embedding'], unique=False, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_response_due_date'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.create_index('idx_opportunities_status', 'opportunities', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_opportunities_due_date', 'opportunities', ['response_due_date'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_opportunities_company', 'opportunities', ['company_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_naics_code'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_customer_agency'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.create_index('idx_documents_type', 'documents', ['document_type'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_documents_status', 'documents', ['processing_status'], unique=False)
    op.create_index('idx_documents_naics', 'documents', ['naics_code'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_documents_embedding', 'documents', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_documents_customer', 'documents', ['customer_agency'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_documents_company', 'documents', ['company_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_companies_uei'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_cage_code'), table_name='companies')
    op.create_index('idx_companies_uei', 'companies', ['uei'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_companies_name', 'companies', ['name'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_companies_cage', 'companies', ['cage_code'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_company', 'audit_logs', ['company_id'], unique=False)
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_analyses_overall_relevance_score'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_opportunity_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_company_id'), table_name='analyses')
    op.create_index('idx_analyses_score', 'analyses', ['overall_relevance_score'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_analyses_opportunity', 'analyses', ['opportunity_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_analyses_created', 'analyses', ['created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_analyses_company', 'analyses', ['company_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('analyses', 'dimensional_scores')
    op.drop_column('analyses', 'evaluator_perspective')
    op.drop_column('analyses', 'red_flags')
    op.drop_column('analyses', 'contract_assessments')
    op.drop_column('analyses', 'requirements_summary')
    op.drop_column('analyses', 'requirements_matrix')
    # ### end Alembic commands ###
